### ISSUE TITLE
Q: why the dependency on `datalad-installer`

### ISSUE THREAD

**Issue by mih** [jsheunis/studyforrest-data-binder#2]
And even `git` and `git-annex`... should these two no be pulled in automatically  by datalad? And the `datalad-installer` is not used in the notebook, do we need it?

**Comment by jsheunis** [comment]
We don't need `datalad-installer`, so that can be removed. I think it is there for legacy reasons of the first time this template repo was created (for a different use case).

**Comment by jsheunis** [comment]
All redundant dependencies removed in b7d977d
