### ISSUE TITLE
Stick to `clone`+`get` and avoid `install`

### ISSUE THREAD

**Issue by mih** [jsheunis/studyforrest-data-binder#3]
In the handbook we have made that transition and it seems to yield a nice flow:

First ones `clone`'s the root dataset of an analysis/project (after which `clone` is no longer a command to remember about).

All other gimme-the-data steps are performed with `get`.

I would suggest to align the notebook with this flow too. As a consequence, the first call to `install` becomes `clone. All subsequent calls to `install` can simply be removed, because the following `get` will automatically perform the previous explicit call, automatically.

**Comment by jsheunis** [comment]
Thanks, I'll update this.

**Comment by jsheunis** [comment]
Updated in 3501167
